import type { CommsMsg } from './types'
import data from './comms.json'

/**
 * The shared channel the four seats talk on. Generated by `npm run comms`
 * from a workflow run journal — see scripts/build-comms.mjs.
 */
export const COMMS = data.messages as unknown as CommsMsg[]
