import type { Interlock, Session } from './types'
import data from './sessions.json'

/**
 * Authored cycles for the four seats, plus the shared host ledger.
 *
 * Generated by `npm run sessions` from a workflow run journal — see
 * scripts/build-sessions.mjs. Edit the JSON directly only for one-off copy
 * fixes; anything structural should be regenerated.
 */
export const SESSIONS = data.sessions as unknown as Session[]
export const INTERLOCK = data.interlock as unknown as Interlock
